name: Edward Frank Real Estate
favicon: null
layout_spectrum: 0.5002926136367023
typography_spectrum: 0.0733328303322196
title: Utah Real Estate Experts
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8881162779871374
  lightness: 0.405134191038087
  saturation: 0.02091904473491013
  rhythmicContrast: 0.10164047032594681
purpose: []
